name: Issue Notification

on:
  issues:
    types: [opened]

permissions:
  issues: read
  actions: write

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Process new issue
        env:
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          TARGET_REPO: ${{ secrets.ISSUE_NOTIFY_TARGET_REPO }}
          TARGET_WORKFLOW: ${{ secrets.ISSUE_NOTIFY_TARGET_WORKFLOW || 'issue-detective.yml' }}
          GH_TOKEN: ${{ secrets.ISSUE_NOTIFY_TOKEN || github.token }}
        run: |
          # Check if internal processing is configured
          if [ -z "$TARGET_REPO" ]; then
            echo "Internal processing not configured"
            exit 0
          fi
          
          echo "Processing issue #${ISSUE_NUMBER}"
          
          # Trigger internal workflow via workflow_dispatch
          gh workflow run ${TARGET_WORKFLOW} \
            --repo ${TARGET_REPO} \
            -f "issue_url=${ISSUE_URL}" 2>/dev/null || {
              echo "Issue notification sent (dispatch may have failed due to permissions)"
              exit 0
            }
          
          echo "✅ Issue processed and dispatched to ${TARGET_REPO}"