name: Issue Notification

on:
  issues:
    types: [opened]

permissions:
  issues: read
  actions: write

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Process new issue
        env:
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          TARGET_REPO: ${{ secrets.ISSUE_NOTIFY_TARGET_REPO }}
          TARGET_WORKFLOW: ${{ secrets.ISSUE_NOTIFY_TARGET_WORKFLOW }}
          GH_TOKEN: ${{ secrets.ISSUE_NOTIFY_TOKEN }}
        run: |
          # Check if internal processing is configured
          if [ -z "$TARGET_REPO" ] || [ -z "$TARGET_WORKFLOW" ]; then
            echo "Not configured"
            exit 0
          fi

          echo "Processing issue #${ISSUE_NUMBER}"

          # Trigger internal workflow via repository_dispatch
          gh api repos/${TARGET_REPO}/dispatches \
            -f event_type=issue_opened \
            -f client_payload[issue_url]="${ISSUE_URL}"|| {
              echo "Issue notification sent"
              exit 0
            }
